### ISSUE TITLE
Feature: Support AssertLog Test

### ISSUE THREAD

**Issue by spacetj** [covarity/anchorctl#23]
### Description
Support the ability to assert the logs of a pod contains / not contains the string that you would expect it too.

### Basic Example

The input would look something like:

```yaml
- type: AssertLog
  spec:
    contains: "Some String"
    lines: 100  # Optionally provides the number of log lines to compare to
  resource:
    objectRef:
      type: Resource
      spec:
        kind: Pod
        namespace: applications
        labels:
          hello: world
```

### Motivation

The Sealed Secrets controller will output a decryption error log if one of the sealed secrets isn't decrypted properly. `anchorctl` should be able to parse the logs and fail the test if the logs contain the phrase "Decryption error"
